Feature/task 16 extended active record capabilities
bdisney/tickets_finder pull request #4
Opened 2017-06-15 11:13 UTC by bdisney

2017-06-15 16:19 UTC, vkurennov requested changes

2017-06-15 16:19 UTC, vkurennov commented on app/controllers/carriages_controller.rb
> +    @carriage = carriage_class.new(carriage_params(carriage_class))
Можно было бы использовать и базовый класс, а  в видах привести объект к базовому типу через метод `becomes`

2017-06-15 16:19 UTC, vkurennov commented on app/models/business_carriage.rb
> +  def self.permitted_params
Не совсем верно это хранить в модели, лучше использовать becomes, как я описал выше.

2017-06-15 18:54 UTC, bdisney commented on app/controllers/carriages_controller.rb
> +    @carriage = carriage_class.new(carriage_params(carriage_class))
Поправил, пока без добавления валидаций.

2017-06-16 07:43 UTC, vkurennov approved these changes

2017-06-16 12:02 UTC, merged